export default {
  CAMPO_LOGIN: 'CAMPO_LOGIN',
  CAMPO_SENHA: 'CAMPO_SENHA',
  BOTAO_ENTRAR: 'BOTAO_ENTRAR',
  BOTAO_MOSTRAR_SENHA: 'BOTAO_MOSTRAR_SENHA',
  BOTAO_ESQUECI_SENHA: 'BOTAO_ESQUECI_SENHA',
  MENSAGEM_ERRO_CAMPO_LOGIN: 'MENSAGEM_ERRO_CAMPO_LOGIN',
  MENSAGEM_ERRO_CAMPO_SENHA: 'MENSAGEM_ERRO_CAMPO_SENHA',

  BOTAO_RESETAR_SENHA: 'BOTAO_RESETAR_SENHA',

  MODAL_VIEW: 'MODAL_VIEW',
  MODAL_BOTAO_OK: 'MODAL_VIEW',
  MODAL_TITULO: 'MODAL_TITULO',
  MODAL_DESCRICAO: 'MODAL_DESCRICAO',

  BOTAO_EXIBIR_MENU: 'BOTAO_EXIBIR_MENU',
  BOTAO_TELA_NOTIFICACOES: 'BOTAO_TELA_NOTIFICACOES',
  BOTAO_ACESSAR_MODULOS: 'BOTAO_ACESSAR_MODULOS',

  // Menu
  MENU_BOTAO_HOME: 'MENU_BOTAO_HOME',
  MENU_BOTAO_ALTERAR_SENHA: 'MENU_BOTAO_ALTERAR_SENHA',
  MENU_BOTAO_NOTIFICACOES: 'MENU_BOTAO_NOTIFICACOES',
  MENU_BOTAO_MODULOS: 'MENU_BOTAO_MODULOS',
  MENU_BOTAO_SAIR: 'MENU_BOTAO_MODULOS',

  CAMPO_PESQUISAR: 'CAMPO_PESQUISAR'
}